import { ReactComponent as Apple } from '../../assets/images/podcasts/apple.svg';
import { ReactComponent as Google } from '../../assets/images/podcasts/google.svg';
import { ReactComponent as Spotify } from '../../assets/images/podcasts/spotify.svg';
const podcastItem = [
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
  {
    name: 'Code Newbie',
    explan: 'Stories and interviews from people on their coding journey.',
    icon: [
      <Apple/>,
      <Google/>,
      <Spotify/>,
    ],
    host: 'Ben Halpern & Jess lee',
    potcastImg: 'bgImg',
    imgAlt: 'Code Newbie',
    bookmark: false,
  },
];

export default podcastItem;